from __future__ import annotations

from decouple import config as env

FLASK_SECRET_KEY = env('FLASK_SECRET_KEY')
# Directory to en-route the flask application and config
FLASK_APP = env('FLASK_APP')

FLASK_RUN_PORT = env('FLASK_RUN_PORT')

# Flask API web framework working environment
FLASK_ENV = env('FLASK_ENV')
# The environment, can be: "local", "test", "producccion"
ENVIRONMENT = env('ENVIRONMENT')

HEADERS = env('HEADERS')

MARVEL_API_PUBLIC_KEY = env('MARVEL_API_PUBLIC_KEY')
MARVEL_API_PRIVATE_KEY = env('MARVEL_API_PRIVATE_KEY')

HTTP_METHODS_ALLOW = env('HTTP_METHODS_ALLOW')
ORIGINS = env('ORIGINS')

LOOKING_FOR_CRITERIA_ACCEPTANCE = env('LOOKING_FOR_CRITERIA_ACCEPTANCE')

MARVEL_URL_HOST = env('MARVEL_URL_HOST')

ENDPOINT_CHARACTERS_ORDERBY_NAME = env('ENDPOINT_CHARACTERS_ORDERBY_NAME')
ENDPOINT_CHARACTERS_BY_NAME = env('ENDPOINT_CHARACTERS_BY_NAME')
ENDPOINT_CHARACTERS_START_NAME = env('ENDPOINT_CHARACTERS_START_NAME')

ENDPOINT_COMIC_BY_TITLE = env('ENDPOINT_COMIC_BY_TITLE')
ENDPOINT_COMIC_START_TITLE = env('ENDPOINT_COMIC_START_TITLE')
